### ISSUE TITLE
Plugin works with only v0.7

### ISSUE THREAD

**Issue by siduck** [numToStr/Comment.nvim#145] opened 2022-04-19 04:46 UTC
I updated the plugin recently and it stopped working

![image](https://user-images.githubusercontent.com/59060246/163921999-766945ed-f80b-4382-8159-5f446e060e89.png)

works for v0.7 tho! 

https://github.com/NvChad/NvChad/issues/957#issuecomment-1102018714

**Comment by numToStr** [comment] 2022-04-19 06:40
Duplicate of https://github.com/numToStr/Comment.nvim/issues/141

**Comment by SunJun8** [comment] 2022-04-19 06:41
Fine!

**Closed by numToStr** 2022-04-19 06:40 UTC
