### ISSUE TITLE
Feature request, work with dot repeat

### ISSUE THREAD

**Issue by mangelozzi** [numToStr/Comment.nvim#307] opened 2023-02-10 12:11 UTC
Say one uses the  `Add comment at the end of line` command to add a comment, then one wishes to add the same comment at the end of another line, pressing the `.` (dot repeat) will only insert the typed text, and not the leading start of comment delimiter:

e.g.

```
foo = 1  <---- place cursor here and run the command add comment at the end of line
bar = 2
```

One then adds the following comment, exit insert mode and move down a line:

```
foo = 1  # Comment.nvim is da shiz
bar = 2 <---- Place cursor here and press dot
```

The result, notice the lack of '#' on the second line:

```
foo = 1  # Comment.nvim is da shiz
bar = 2 Comment.nvim is da shiz
```

**Comment by bew** [comment] 2023-02-10 13:58
Duplicate of #222
I've been meaning to properly fix it, but didn't spend time on it yet..

**Comment by numToStr** [comment] 2023-02-10 15:07
As @bew mentioned this is a duplicate. My stand is that this behaviour is nice to have but I won't be able to implement this as I don't have much time on my hand nowadays but I'll gladly accept a PR which implements this behaviour, though not in a hacky way.

Closing this for now :)

**Closed** 2023-02-10 15:08 UTC
