### ISSUE TITLE
bug: the latex parser is not properly registered for the `tex` filetype when commenting

### ISSUE THREAD

**Issue by mathjiajia** [numToStr/Comment.nvim#325] opened 2023-04-10 13:42 UTC
Describe the bug:

```
Error executing vim.schedule lua callback: ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'tex' language, see :help treesitter-parsers
stack traceback:
[C]: in function 'error'
...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: in function 'add'
...l/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:88: in function 'new'
/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
/usr/local/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:106: in function 'get_folds_levels'
/usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:196: in function </usr/local/share/nvim/runtime/lua/vim/treesitter/_fold.lua:193>
```

-----------------------
the output of :=vim.treesitter.language.get_filetypes('latex') before and after the error
before: `{ "latex", "cls", "sty", "tex" }`
after" `{ "latex", "cls", "sty" }`

-----------------------
You may try the minimal `init.lua` below:

1, open any `latex` file (say `abc.tex`) with nvim;
2, toggle comment with `gcc`.

```lua
local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'

	use {
		"numToStr/Comment.nvim",
		config = function()
			require('Comment').setup()
		end,
		}
    use {
			'nvim-treesitter/nvim-treesitter',
      run = ':TSUpdate',
			config = function()
				-- Folding
				vim.opt.foldmethod = "expr"
				vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
				vim.opt.foldenable = false

				require("nvim-treesitter.configs").setup({
					ensure_installed = { "latex" },
					highlight = { enable = true },
				})
			end,
    }

		if packer_bootstrap then
			require('packer').sync()
		end
end)
```

See also https://github.com/nvim-treesitter/nvim-treesitter/issues/4630#issuecomment-1501822842
https://github.com/neovim/neovim/issues/22974

**Comment by tbung** [comment] 2023-04-11 10:58
This seems to also be happening with `bash`/`sh`.

`init.lua`
```lua
local ensure_packer = function()
  local fn = vim.fn
  local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
  if fn.empty(fn.glob(install_path)) > 0 then
    fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
    vim.cmd [[packadd packer.nvim]]
    return true
  end
  return false
end

local packer_bootstrap = ensure_packer()

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'

	use {
		"numToStr/Comment.nvim",
		config = function()
			require('Comment').setup()
		end,
		}
    use {
			'nvim-treesitter/nvim-treesitter',
      run = ':TSUpdate',
			config = function()
				-- Folding
				vim.opt.foldmethod = "expr"
				vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
				vim.opt.foldenable = false

				require("nvim-treesitter.configs").setup({
					ensure_installed = { "bash" },
					highlight = { enable = true },
				})
			end,
    }

		if packer_bootstrap then
			require('packer').sync()
		end
end)
```

`test.sh`
```bash
#!/bin/bash

function foo() {
    printf "test"
}
```

When opening the file, `:=vim.treesitter.language.get_filetypes('bash')` gives
```
{ "bash", "sh", "PKGBUILD" }
```
and `:=vim.treesitter.language.get_filetypes('sh')` gives `{}`.

After triggering the error with comment.nvim, `:=vim.treesitter.language.get_filetypes('bash')` gives
```
{ "bash", "PKGBUILD" }
```
and `:=vim.treesitter.language.get_filetypes('sh')` gives `{ "sh" }`.

**Comment by tbung** [comment] 2023-04-11 11:19
I am not too deep in the treesitter development, so I don't know if this is an issue with `nvim-treesitter` or intended behaviour and therefore an issue with `Comment.nvim`, but a fix for this issue would be to change https://github.com/numToStr/Comment.nvim/blob/master/lua/Comment/ft.lua#L252 to get the registered `lang` for a filetype:

```lua
local parsername = filetype_to_parsername[filetype] or vim.treesitter.language.get_lang(filetype)
```

**Closed** 2023-04-11 12:56 UTC
