### ISSUE TITLE
help wanted: vim.keymap is nil with nvim 0.6.1

### ISSUE THREAD

**Issue by stark-zhang** [numToStr/Comment.nvim#150] opened 2022-04-22 13:18 UTC
as title said, the first line in [`after/plugin/Comments.nvim`](https://github.com/numToStr/Comment.nvim/blob/master/after/plugin/Comment.lua) has reported an error with nvim 0.6.1 like the screenshot:

![image](https://user-images.githubusercontent.com/17326718/164720122-228b55d1-2b77-44b8-90f3-cd3a37983072.png)

is this table, named `vim.keymap`, on nvim 0.7 only? or what happened in the processing? it works well with nvim 0.7. I think you could make a notice about this breaking change in README.md.

**Comment by numToStr** [comment] 2022-04-22 13:21
Duplicate of #141

**Comment by numToStr** [comment] 2022-04-22 13:22
Also please follow #114 to get notified about breaking changes.

**Closed by numToStr** 2022-04-22 13:21 UTC
Labels: duplicate

**Comment by stark-zhang** [comment] 2022-04-22 13:25
got it.
