### ISSUE TITLE
[Feature Request] don't count empty line when toggle comment.

### ISSUE THREAD

**Issue by shaeinst** [numToStr/Comment.nvim#229] opened 2022-09-04 12:16 UTC
current behavior
```lua
{
	// int i, avail, new_len;
	// unsigned char *ptr;
	// struct sk_buff *skb;

	// if (!ab)
	// 	return;
} 

after toggling 

{
	// // int i, avail, new_len;
	// // unsigned char *ptr;
	// // struct sk_buff *skb;
	//
	// // if (!ab)
	// // 	return;
} 
```

Expected behavior
```lua
{
	// int i, avail, new_len;
	// unsigned char *ptr;
	// struct sk_buff *skb;

	// if (!ab)
	// 	return;
} 

after toggling 

{
	int i, avail, new_len;
	unsigned char *ptr;
	struct sk_buff *skb;

	if (!ab)
		return;
} 
```

**Comment by numToStr** [comment] 2022-09-04 12:21
Duplicate of #213

**Closed** 2022-09-04 12:21 UTC

**Comment by shaeinst** [comment] 2022-09-04 12:50
problem with this is, when you comment block of comment with empty line, its going to ignore empty line. 
>require'Comment'.setup({ ignore = '^$' })

it make more sense like this:
on toggle:
if selected block is uncommented and has empty line -> then comment (non-empty line + empty line).
if selected block is commented and has empty line -> then un-comment

**Comment by numToStr** [comment] 2022-09-04 12:53
> it make more sense like this:

To me, it doesn't. Either you consider or ignore empty lines all the times, no special handling.
