### ISSUE TITLE
[feature] Support for pasting current line/selection as a comment above/below

### ISSUE THREAD

**Issue by AniAggarwal** [numToStr/Comment.nvim#255] opened 2022-10-07 21:15 UTC
I find myself often copy-pasting a line or selection and then commenting out the original so that I can make some changes but still preserve the original if I want to revert. I'd love if there was native support for this as I've tried to create a mapping but it's been quite janky.

Example usage:
```
pr|int("just some code here that I want to change but preserve")
foo(bar)
```
\> `gcp` with cursor anywhere on first line
```
# print("just some code here that I want to change but preserve")
|print("just some code here that I want to change but preserve")
foo(bar)
```

Similar behavior with selections, with `gcp` pastes below and `gcP` pastes above and `gbp` and `gbP` doing the same but with block comments.

**Comment by numToStr** [comment] 2022-10-08 04:51
Duplicate of #70. Please search issue tracker first for similar issues.

**Closed** 2022-10-08 04:52 UTC
Labels: duplicate

**Comment by AniAggarwal** [comment] 2022-10-08 11:54
Sorry, must have missed it! I can't quite get that one to work though (I'll comment on that thread).

**Comment by numToStr** [comment] 2022-10-08 11:58
There is also a discussion thread about the same (or create one?). Please follow that instead of commenting on a different issue.
