### ISSUE TITLE
Commenting visual block does not seem to work

### ISSUE THREAD

**Issue by fikovnik** [numToStr/Comment.nvim#208] opened 2022-08-19 11:28 UTC
When I select a few lines and do `gcc`, I get the following error:

```
E5108: Error executing lua ...va/.config/nvim/plugged/Comment.nvim/lua/Comment/api.lua:19: attempt to call field 'd
eprecate' (a nil value)
stack traceback:
        ...va/.config/nvim/plugged/Comment.nvim/lua/Comment/api.lua:19: in function 'D'
        ...va/.config/nvim/plugged/Comment.nvim/lua/Comment/api.lua:473: in function '__index'
        [string ":lua"]:1: in main chunk
```

I'm on the latest version (ab63cc90d9cc2bcc93d8a24c4fae2ea4ed0795f1) running nvim 0.7.2.
I do not have any extra configuration over the single call to setup.

Any idea what could be wrong?
Thank you, much appreciate the plugin!

**Comment by numToStr** [comment] 2022-08-19 11:37
I doubt that the default keybindings would've caused. The cause of error was introduced a week ago cd1c38163dd9a11247bcb333d72a36bae76c45f9 and the error is coming because somewhere old API is used, precisely `require('Comment.api').locked.*` API.

Are you, by any chance, using a nvim distro? like NvChad, AstroVim etc.

**Comment by fikovnik** [comment] 2022-08-19 13:40
No, I have my own nvim config.

**Comment by numToStr** [comment] 2022-08-19 13:42
Would you mind reproducing the issue with a minimal `init.lua`?

**Comment by vanarok** [comment] 2022-08-20 12:35
![2022-08-20T16:35:11,169859442+04:00](https://user-images.githubusercontent.com/6105977/185746462-183076a9-c4ce-4038-8250-be6cb1fc12aa.png)

**Comment by numToStr** [comment] 2022-08-20 12:38
@vanarok https://github.com/neovim/neovim/issues/19857

**Comment by numToStr** [comment] 2022-08-22 06:21
I am going to close this for now as I can't reproduce this myself and other people doesn't seem to be facing this.

**Closed by numToStr** 2022-08-22 06:21 UTC
Labels: invalid
